# version: "3.8"
# services:
#   react-app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     volumes:
#       - ./:/src
#     command: sh -c "cd app && PORT=3001 yarn start"
#     # command: sh -c 'cd frontend && yarn start'
#     ports:
#       - "3001:3001"
#     stdin_open: true

# version: "3"
# services:
#   node:
#     build:
#       context: .
#     tty: true
#     environment:
#       - CHOKIDAR_USEPOLLING=true
#     volumes:
#       - ./:/usr/src/app
#     command: sh -c "cd app && yarn start"
#     ports:
#       - "3000:3000"

version: "3.8"
services:
  front:
    build: ./
    container_name: node
    volumes:
      - ./front:/front
    working_dir: /front
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true //ホットリロードを行う設定
